Traceback (most recent call last):
  File "C:\Users\rorodri\AppData\Local\Programs\Python\Python39\lib\site-packages\jupyter_cache\executors\utils.py", line 51, in single_nb_execution
    executenb(
  File "C:\Users\rorodri\AppData\Local\Programs\Python\Python39\lib\site-packages\nbclient\client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\rorodri\AppData\Local\Programs\Python\Python39\lib\site-packages\nbclient\util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "C:\Users\rorodri\AppData\Local\Programs\Python\Python39\lib\site-packages\nbclient\util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "C:\Users\rorodri\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "C:\Users\rorodri\AppData\Local\Programs\Python\Python39\lib\site-packages\nbclient\client.py", line 553, in async_execute
    await self.async_execute_cell(
  File "C:\Users\rorodri\AppData\Local\Programs\Python\Python39\lib\site-packages\nbclient\client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "C:\Users\rorodri\AppData\Local\Programs\Python\Python39\lib\site-packages\nbclient\client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import pandas as pd
from itables import init_notebook_mode

init_notebook_mode(all_interactive=True)

def make_clickable(id,name):
    return f'<a href="https://threathunterplaybook.com/hunts/windows/{id}/notebook.html">{name}</a>'

df = pd.read_csv('analytic_summary.csv')
df['Title'] = df.apply(lambda x: make_clickable(x['Id'], x['Title']), axis=1)
df.drop('Id', axis=1, inplace=True)
show(
    df,
    columnDefs=[{"width": "100px", "targets": "_all"}],
)
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mNameError[0m                                 Traceback (most recent call last)
[1;32m<ipython-input-1-f317b0ee98c8>[0m in [0;36m<module>[1;34m[0m
[0;32m     10[0m [0mdf[0m[1;33m[[0m[1;34m'Title'[0m[1;33m][0m [1;33m=[0m [0mdf[0m[1;33m.[0m[0mapply[0m[1;33m([0m[1;32mlambda[0m [0mx[0m[1;33m:[0m [0mmake_clickable[0m[1;33m([0m[0mx[0m[1;33m[[0m[1;34m'Id'[0m[1;33m][0m[1;33m,[0m [0mx[0m[1;33m[[0m[1;34m'Title'[0m[1;33m][0m[1;33m)[0m[1;33m,[0m [0maxis[0m[1;33m=[0m[1;36m1[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0;32m     11[0m [0mdf[0m[1;33m.[0m[0mdrop[0m[1;33m([0m[1;34m'Id'[0m[1;33m,[0m [0maxis[0m[1;33m=[0m[1;36m1[0m[1;33m,[0m [0minplace[0m[1;33m=[0m[1;32mTrue[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[1;32m---> 12[1;33m show(
[0m[0;32m     13[0m     [0mdf[0m[1;33m,[0m[1;33m[0m[1;33m[0m[0m
[0;32m     14[0m     [0mcolumnDefs[0m[1;33m=[0m[1;33m[[0m[1;33m{[0m[1;34m"width"[0m[1;33m:[0m [1;34m"100px"[0m[1;33m,[0m [1;34m"targets"[0m[1;33m:[0m [1;34m"_all"[0m[1;33m}[0m[1;33m][0m[1;33m,[0m[1;33m[0m[1;33m[0m[0m

[1;31mNameError[0m: name 'show' is not defined
NameError: name 'show' is not defined

